config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get "todos", to: "todos#index"
  #post "todos/create", to: "todos#create"
  #get "todos/:id", to: "todos#show"
  resources :todos, :users
  post "users/:id/login", to: "users#login"
  get "sign_in", to: "sessions#new", as: :new_session
  post "/sign_in", to: "sessions#create", as: :session
  root to: "home#index"
  delete "/signout", to: "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :todo_text, presence: true, length: { in: 3..50 }
  validates :due_date, presence: true

  def to_pleasant_string
    status = completed ? "[X]" : "[ ]"
    "#{id}. #{due_date.to_s(:short)} #{todo_text} #{status}"
  end

  def self.overdue
    where("due_date < ? and completed = ?", Date.parse(Date.today.to_s), false)
  end

  def self.due_today
    where("due_date = ?", Date.parse(Date.today.to_s))
  end

  def self.due_later
    where("due_date > ?", Date.parse(Date.today.to_s))
  end

  def self.completed_todos
    where("completed = ?", true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :todos, dependent: :destroy
  validates :first_name, :password, presence: true, length: { in: 3..50 }
  validates :email, presence: true, uniqueness: true

  def to_pleasant_string
    "#{id}. Name:#{name} Email:#{email} Password:#{password}"
  end

  def self.check_crendentials(email, password)
    where("email=? and password=?", email, password).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      flash[:notice] = "You need to sign-in before continuing"
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    if current_user
      flash[:notice] = "You're already signed in user!"
      redirect_to root_path
    end
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      flash[:notice] = "Your login is successful!"
      redirect_to todos_path
    elsif user
      flash[:alert] = "Invalid email and password"
      redirect_to new_session_path
    else
      flash[:alert] = "Account associated with #{params[:email]} not found"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    flash[:notice] = "You're logged out successfully!"
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
  end

  def show
    id = params[:id]
    render plain: Todo.find(id).to_pleasant_string
  end

  def create
    todo = params[:todo]
    todo_text = todo[:todo_text]
    due_date = todo[:due_date].empty? ? nil : Date.parse(todo[:due_date])
    new_todo = Todo.new(todo_text: todo_text, due_date: due_date, completed: false, user_id: current_user.id)
    if new_todo.save
      #TodoMailer.with(todo_text: new_todo.todo_text, due_date: new_todo.due_date, email: @current_user.email, name: @current_user.first_name).upcoming_todo.deliver_now
      flash[:notice] = "Your todo is successfully created"
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    current_user.todos.find(params[:id]).destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    if current_user
      flash[:notice] = "You're already created account!"
      redirect_to root_path
    end
  end

  def index
    render plain: User.all.map { |user| user.to_pleasant_string }.join("\n")
  end

  def show
    id = params[:id]
    render plain: User.find(id).to_pleasant_string
  end

  def create
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    password = params[:password]
    new_user = User.new(first_name: first_name, last_name: last_name, email: email, password: password)
    if new_user.save
      flash[:notice] = "Hello! Welcome #{first_name}"
      session[:current_user_id] = new_user.id
      redirect_to todos_path
    else
      flash[:error] = new_user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def login
    email = params[:email]
    password = params[:password]
    render plain: User.check_crendentials(email, password)
  end

  def edit
    current_user
  end

  def update
    user = current_user
    password = params[:password]
    password_confirmation = params[:password_confirmation]
    current_password = params[:current_password]
    if user.authenticate(current_password)
      if password == password_confirmation
        flash[:notice] = "Password updated successfully"
        user.update!(password: password)
        redirect_to todos_path
      else
        flash[:alert] = "New passwords doesnt match"
        redirect_to edit_user_path
      end
    else
      flash[:alert] = "Your current password is incorrect"
      redirect_to edit_user_path
    end
  end

  def destroy
    current_user.destroy
    session[:current_user_id] = nil
    @current_user = nil
    flash[:notice] = "Your account deleted successfully!Hope you will be back"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<main class="main-body">
  <p class="img-welcomeLeft">
    <img src="welcome-left.png">
  </p>
  <h2 class="home-h2">Organise Your <br>
    todos now<br>
    <%= link_to "Get started", new_session_path, class:"get-started" %>
  </h2>
  <p class="img-welcomeRight">
    <img src="welcome-right.png">
  </p>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="Header"> Todo Management
      <%if @current_user%>
        <ul>
          <li class="header-greetings">Hello
            <%= @current_user.first_name.capitalize %>
          </li>
          <li class="header-buttons">
            <%= link_to "Edit Profile", edit_user_path(@current_user.id) %>
          </li>
          <li class="header-buttons">
            <%= link_to "Log Out",
                        destroy_session_path,
                        method: "delete",
                        data: {confirm:'Are you sure to logOut'}
            %>
          </li>
        </ul>
      <% else %>
        <ul>
          <li class="header-buttons">
            <%= link_to "Sign In", new_session_path %>
          </li>
          <li class="header-buttons">
            <%= link_to "Sign Up", new_user_path %>
          </li>
        </ul>
      <%end%>
    </header>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <%end%>
    <% if flash.alert %>
      <p class="alert"><%= alert %></p>
    <%end%>
    <% if flash[:error] %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(flash[:error].count, "error") %> prohibited this todo from being saved:
        </h2>
        <ul>
          <% flash[:error].each_with_index do |msg,index| %>
            <li><%= "#{index + 1}.#{msg}" %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= yield %>
    <footer class="Footer"> &copy; All copyrights are reserved.</footer>
  </body>
</html>

app/views/todos/_todosection-todo.html.erb
<ul class="TodoSection">
  <h2 class="TodoSection-title">  <%= todo_heading %>
    <span class="TodoSection-status">
      <%= todos.completed_todos.count %>/<%= todos.count %>
    </span>
  </h2>
  <% todos.each do |todo| %>
    <li class="TodoSection-todo" >
      <label class="todos-lable" for=<%= todo.id %> >
        <%= form_with( url: "todos/#{todo.id}" , method: "PUT" ) do%>
          <input class="TodoSection-todoCheckbox"
                 name="completed"
                 onclick = this.form.submit()
                 id=<%= todo.id %>
                 type="checkbox"
                 <%= todo.completed ? "checked" : "" %>
          >
        <% end %>
        <span <% if todo.completed %>
              style="text-decoration:line-through"
               <% end %>
        >
          <%= todo.todo_text.capitalize %>
        </span>
        <% if show_date %>
          <span class="TodoSection-dueDate">
            <%= todo.due_date.to_s(:short) %>
          </span>
        <% end %>
      </label>
      <%= link_to todo, method: :delete, data: {confirm: 'Are you sure?'} do %>
        <%= image_tag "trash.png", class: "TodoSection-todoDelete" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/todos/index.html.erb
<article class="main-todoBody">
  <h1 class="Todo-title">My Todo-List</h1>
  <%= form_with scope: :todo, local: true, class:"todoAdd-form" do |form| %>
    <%= form.text_field :todo_text,
                        class:"Todo-addBox",
                        placeholder: "What's next?",
                        autofocus:"autofocus"
    %>
    <%= form.date_field :due_date,
                        class:"Todo-Calender",
                        placeholder:"DD/MM/YY",
                        autofocus:"autofocus"
    %>
    <%= form.submit "Add",
                    class:"Todo-AddButton",
                    placeholder:"Add" %>
  <%end%>
  <%= render partial: "todosection-todo",
             locals: {todo_heading: "Overdue",
                      todos: @current_user.todos.overdue ,
                      show_date: true ,
                      overdue: true }
  %>
  <%= render partial: "todosection-todo",
             locals: {todo_heading: "Due Today",
                      todos: @current_user.todos.due_today ,
                      show_date: false,
                      overdue:false }
  %>
  <%= render partial: "todosection-todo",
             locals: {todo_heading: "Due Later",
                      todos: @current_user.todos.due_later ,
                      show_date: true ,overdue:false} %>
</article>

app/views/users/edit.html.erb
<main class="updateUser-box">
  <%= form_with url: user_path, method: :put,id: "edit_user" do |form| %>
    <%= form.password_field :password,
                             placeholder: "Password",
                             autofocus:"autofocus"
    %>
    <br>
    <%= form.password_field :password_confirmation,
                             placeholder: "Conifrm new Password",
                             autofocus: true
    %>
    <br>
    <%= form.password_field :current_password,
                             placeholder: "Current Password",
                             autofocus: "autofocus"
    %>
    <br>
    <%= form.submit "Update" %>
  <% end %>
  <h3 class="updateUser-cancelAccount">
    Unhappy? Cancel my account
    <%= button_to "Cancel my account",
                  user_path,
                  data: { confirm: "Are you sure?" },
                  method: :delete
    %>
  </h3>
  <%= link_to "Back to Todos", :back %>
</main>

app/views/users/new.html.erb
<main class="signUpBox">
  <p class="signUp-login">
    Already have an account?
    <%= link_to "Login here", new_session_path, class:"login-link" %>
  </p>
  <%= form_with url: users_path, class: "signUp-form" do |form| %>
    <%= form.text_field :first_name,
                         placeholder: "First Name",
                         autofocus:"autofocus"
    %>
    <br>
    <%= form.text_field :last_name,
                         placeholder: "Last Name",
                         autofocus:"autofocus"
    %>
    <br>
    <%= form.email_field :email,
                          placeholder: "Email",
                          autofocus:"autofocus"
    %>
    <br>
    <%= form.password_field :password,
                             placeholder: "Password",
                             autofocus:"autofocus"
    %>
    <br>
    <%= form.submit "Sign up", class: "signUp-button"%>
  <%end%>
</main>